"""Render scan results as a self-contained HTML report.

No network calls at view time. CSS + JS are inlined from report/assets.py.
"""

from __future__ import annotations

import datetime as dt
import html
import re
from string import Template
from typing import Optional

from scs.findings import Finding, RepoReport, Severity
from scs.report.assets import CSS_TEXT, JS_TEXT


_INVALID_ID = re.compile(r"[^a-zA-Z0-9_-]")


def _slug(s: str) -> str:
    return _INVALID_ID.sub("-", s).strip("-").lower() or "repo"


_HTML_TEMPLATE = Template("""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>scs report — $title</title>
<style>$css</style>
</head>
<body>
$sidebar
<main>
$banners
$body
<footer>Generated by <code>scs $version</code> on $generated_at · $repo_count repo(s) · $finding_count finding(s)</footer>
</main>
<script>$js</script>
</body>
</html>
""")


def render_html(
    repos: list[RepoReport],
    *,
    version: str = "0.1.0",
    build_ts: Optional[str] = None,
    malware_db_path: Optional[str] = None,
    malware_db_built_at: Optional[int] = None,
    malware_db_sha256: Optional[bytes] = None,
    malware_db_entries: Optional[int] = None,
    malware_db_keys: Optional[int] = None,
    malware_db_status: str = "",
    enrichment_skipped: bool = False,
) -> str:
    title = f"{len(repos)} repo{'s' if len(repos) != 1 else ''}"
    body = "\n".join(_render_repo(r) for r in repos) if repos else _empty_state()
    banners = _render_banners(malware_db_status, enrichment_skipped)
    generated_at = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return _HTML_TEMPLATE.substitute(
        title=html.escape(title),
        css=CSS_TEXT,
        js=JS_TEXT,
        sidebar=_render_sidebar(
            repos,
            version=version,
            build_ts=build_ts,
            malware_db_path=malware_db_path,
            malware_db_built_at=malware_db_built_at,
            malware_db_sha256=malware_db_sha256,
            malware_db_entries=malware_db_entries,
            malware_db_keys=malware_db_keys,
            generated_at=generated_at,
        ),
        banners=banners,
        body=body,
        version=html.escape(version),
        generated_at=html.escape(generated_at),
        repo_count=len(repos),
        finding_count=sum(len(r.findings) for r in repos),
    )


def _render_sidebar(
    repos: list[RepoReport],
    *,
    version: str,
    build_ts: Optional[str],
    malware_db_path: Optional[str],
    malware_db_built_at: Optional[int],
    malware_db_sha256: Optional[bytes],
    malware_db_entries: Optional[int],
    malware_db_keys: Optional[int],
    generated_at: str,
) -> str:
    parts = ['<aside class="sidebar">']
    parts.append('<h1>scs</h1>')
    parts.append('<div class="meta">supply-chain exposure scanner</div>')

    # Metadata table
    parts.append('<table class="meta-table"><tbody>')
    parts.append(f'<tr><td>Report</td><td>{html.escape(generated_at)}</td></tr>')
    parts.append(f'<tr><td>Scanner</td><td>{html.escape(version)}</td></tr>')
    if build_ts:
        parts.append(f'<tr><td>Built</td><td>{html.escape(build_ts)}</td></tr>')
    else:
        parts.append('<tr><td>Built</td><td>(source)</td></tr>')
    if malware_db_path:
        from pathlib import Path
        parts.append(f'<tr><td>Vuln&nbsp;DB</td><td>{html.escape(Path(malware_db_path).name)}</td></tr>')
        if malware_db_sha256:
            parts.append(f'<tr><td>DB&nbsp;sha256</td><td>{malware_db_sha256.hex()[:16]}…</td></tr>')
        if malware_db_built_at:
            built_iso = dt.datetime.fromtimestamp(malware_db_built_at, tz=dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            parts.append(f'<tr><td>DB&nbsp;built</td><td>{html.escape(built_iso)}</td></tr>')
        if malware_db_entries is not None and malware_db_keys is not None:
            parts.append(f'<tr><td>DB&nbsp;size</td><td>{malware_db_entries:,} / {malware_db_keys:,} pkgs</td></tr>')
    else:
        parts.append('<tr><td>Vuln&nbsp;DB</td><td>(not loaded)</td></tr>')
    parts.append('</tbody></table>')

    parts.append('<div class="nav-section">Repositories</div>')
    parts.append('<nav class="nav">')
    for r in repos:
        sid = "repo-" + _slug(r.name)
        parts.append(
            f'<a href="#{sid}"><span>{html.escape(r.name)}</span>'
            f'<span class="grade grade-{r.grade}">{r.grade}</span></a>'
        )
    parts.append('</nav>')
    parts.append('</aside>')
    return "\n".join(parts)


def _render_banners(malware_db_status: str, enrichment_skipped: bool) -> str:
    out = []
    if malware_db_status:
        cls = "banner"
        if "loaded" not in malware_db_status.lower():
            cls += " warn"
        out.append(f'<div class="{cls}">{html.escape(malware_db_status)}</div>')
    if enrichment_skipped:
        out.append('<div class="banner">Live OSV / registry enrichment skipped (offline mode). Findings reflect static analysis only.</div>')
    return "\n".join(out)


def _empty_state() -> str:
    return '<div class="empty">No repositories found in the given paths. Pass one or more directories that contain a <code>.git</code> dir or a manifest file.</div>'


def _render_repo(r: RepoReport) -> str:
    sid = "repo-" + _slug(r.name)
    counts = r.severity_counts()
    has_findings = bool(r.findings)
    total = max(1, sum(counts.values()))

    bar_cells = "".join(
        f'<div class="b-{cls}" style="width: {round(counts[s] / total * 100, 2)}%"></div>'
        for s, cls in [
            (Severity.CRITICAL, "crit"),
            (Severity.HIGH, "high"),
            (Severity.MEDIUM, "med"),
            (Severity.LOW, "low"),
            (Severity.INFO, "info"),
        ]
        if counts[s] > 0
    )

    cards = []
    cards.append(_card(r.deps_total, "deps", ""))
    cards.append(_card(r.deps_unpinned, "unpinned", "high" if r.deps_unpinned else ""))
    cards.append(_card(counts[Severity.CRITICAL], "critical", "crit" if counts[Severity.CRITICAL] else ""))
    cards.append(_card(counts[Severity.HIGH], "high", "high" if counts[Severity.HIGH] else ""))
    cards.append(_card(counts[Severity.MEDIUM], "medium", "med" if counts[Severity.MEDIUM] else ""))
    cards.append(_card(counts[Severity.LOW], "low", "low" if counts[Severity.LOW] else ""))
    cards.append(_card(r.files_scanned, "files scanned", ""))

    eco_html = "".join(
        f'<span class="eco-tag">{html.escape(e)}</span>' for e in sorted(set(r.ecosystems))
    )
    parts = [f'<section class="repo" id="{html.escape(sid)}">']
    parts.append('<div class="repo-header">')
    parts.append(
        f'<h2>{html.escape(r.name)} <span class="grade grade-{r.grade}">{r.grade}</span></h2>'
    )
    parts.append(f'<div class="path">{html.escape(r.path)}</div>')
    parts.append('<div class="ecos">' + (eco_html or '<span class="eco-tag">no manifests detected</span>') + '</div>')
    parts.append('</div>')
    if r.error:
        parts.append(f'<div class="banner err">Error: {html.escape(r.error)}</div>')

    if not has_findings:
        # Healthy project — celebratory banner
        parts.append(
            '<div class="clean-banner">'
            '<span class="check">✓</span>'
            '<div>'
            '<div class="label">Clean scan — no supply-chain exposure detected</div>'
            f'<div class="sub">{r.deps_total} dep(s) across {r.files_scanned} file(s); '
            "all pinned, locked, integrity-verified, and absent from the malware DB.</div>"
            '</div>'
            '</div>'
        )

    parts.append('<div class="summary">')
    parts.extend(cards)
    parts.append('</div>')
    if bar_cells:
        parts.append(f'<div class="bar">{bar_cells}</div>')
    if has_findings:
        parts.append(_render_findings_table(r.findings))
    parts.append('</section>')
    return "\n".join(parts)


def _card(num: int, label: str, cls: str = "") -> str:
    cls_attr = f' {cls}' if cls else ''
    return f'<div class="card{cls_attr}"><div class="num">{num}</div><div class="label">{html.escape(label)}</div></div>'


def _render_findings_table(findings: list[Finding]) -> str:
    rows = []
    NCOLS = 7  # Severity, Code, Title, Package, Spec, Location, Toggle
    for f in sorted(findings, key=lambda x: x.sort_key()):
        loc = f"{html.escape(f.file)}{':' + str(f.line) if f.line else ''}"

        # Advisory link goes into the expander row now (table is too dense to
        # keep it as a column).
        adv_link = ""
        if f.advisory_id:
            url = f.advisory_url or f"https://osv.dev/vulnerability/{f.advisory_id}"
            adv_link = (
                f'<div class="chain-row"><strong>Advisory:</strong> '
                f'<a href="{html.escape(url)}" target="_blank" rel="noopener noreferrer">'
                f'{html.escape(f.advisory_id)}</a></div>'
            )

        # Build expandable detail (chain, detail text, aliases, advisory, suggestion).
        chain_str = " → ".join(f.chain) + (" → " + f.package if f.chain else "")
        detail_blocks = []
        if f.detail:
            detail_blocks.append(f'<div class="detail-text">{html.escape(f.detail)}</div>')
        if f.chain:
            detail_blocks.append(
                f'<div class="chain-row"><strong>Dep chain:</strong> '
                f'<code>{html.escape(chain_str)}</code></div>'
            )
        if f.aliases:
            detail_blocks.append(
                f'<div class="chain-row"><strong>Aliases:</strong> '
                + ", ".join(html.escape(a) for a in f.aliases) + '</div>'
            )
        if adv_link:
            detail_blocks.append(adv_link)
        if f.suggestion:
            detail_blocks.append(
                f'<div class="fix-block"><span class="label">Suggested fix</span>\n{html.escape(f.suggestion)}</div>'
            )
        has_detail = bool(detail_blocks)
        toggle = '<span class="toggle" title="show details">▶</span>' if has_detail else ''

        rows.append(
            '<tr>'
            f'<td><span class="sev sev-{f.severity.name}">{f.severity.name}</span></td>'
            f'<td><div class="clamp2"><code>{html.escape(f.code)}</code></div></td>'
            f'<td><div class="clamp2">{html.escape(f.title)}</div></td>'
            f'<td><div class="clamp2"><code>{html.escape(f.package)}</code></div></td>'
            f'<td><div class="clamp2"><code>{html.escape(f.spec or f.resolved_version)}</code></div></td>'
            f'<td class="mono"><div class="clamp2">{loc}</div></td>'
            f'<td>{toggle}</td>'
            '</tr>'
        )
        if has_detail:
            rows.append(
                f'<tr class="expand-row"><td colspan="{NCOLS}">' + "\n".join(detail_blocks) + '</td></tr>'
            )

    return (
        '<div class="table-wrap"><table class="findings">'
        '<colgroup>'
        '<col class="col-sev">'
        '<col class="col-code">'
        '<col class="col-title">'
        '<col class="col-pkg">'
        '<col class="col-spec">'
        '<col class="col-loc">'
        '<col class="col-toggle">'
        '</colgroup>'
        '<thead><tr>'
        '<th data-col="0">Severity</th>'
        '<th data-col="1">Code</th>'
        '<th data-col="2">Title</th>'
        '<th data-col="3">Package</th>'
        '<th data-col="4">Spec / Version</th>'
        '<th data-col="5">Location</th>'
        '<th></th>'
        '</tr></thead>'
        '<tbody>' + "\n".join(rows) + '</tbody>'
        '</table></div>'
    )
